# Generated by Django 4.2.12 on 2026-01-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeinstallment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feeinstallment',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='feeinstallment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentfeeallocation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentfeeallocation',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='studentfeeallocation',
            name='updated_at',
        ),
    ]
