# Generated by Django 5.2.10 on 2026-01-15 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PARENT'}, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
