# Generated by Django 4.2.12 on 2026-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_exam_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
