# Generated by Django 4.2.12 on 2026-01-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
